//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResGeneral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResGeneral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResGeneral", typeof(GlobalResGeneral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Contact Tehcnical.
        /// </summary>
        public static string lblContactTechnical {
            get {
                return ResourceManager.GetString("lblContactTechnical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter All Input.
        /// </summary>
        public static string lblInsertInput {
            get {
                return ResourceManager.GetString("lblInsertInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Quota.
        /// </summary>
        public static string lblLabourMenuDesc {
            get {
                return ResourceManager.GetString("lblLabourMenuDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login HQ.
        /// </summary>
        public static string lblLoginHQMsg {
            get {
                return ResourceManager.GetString("lblLoginHQMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login.
        /// </summary>
        public static string lblLoginInvalid {
            get {
                return ResourceManager.GetString("lblLoginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string lblSelectAll {
            get {
                return ResourceManager.GetString("lblSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string menuDashboard {
            get {
                return ResourceManager.GetString("menuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string menuHome {
            get {
                return ResourceManager.GetString("menuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Absconded.
        /// </summary>
        public static string menuLabourAbsconded {
            get {
                return ResourceManager.GetString("menuLabourAbsconded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour End Contract.
        /// </summary>
        public static string menuLabourEndContract {
            get {
                return ResourceManager.GetString("menuLabourEndContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Fomema.
        /// </summary>
        public static string menuLabourFomema {
            get {
                return ResourceManager.GetString("menuLabourFomema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Management.
        /// </summary>
        public static string menuLabourManagement {
            get {
                return ResourceManager.GetString("menuLabourManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour On Leave.
        /// </summary>
        public static string menuLabourOnLeave {
            get {
                return ResourceManager.GetString("menuLabourOnLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Permit Passport.
        /// </summary>
        public static string menuLabourPrmtPsport {
            get {
                return ResourceManager.GetString("menuLabourPrmtPsport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Quota.
        /// </summary>
        public static string menuLabourQuota {
            get {
                return ResourceManager.GetString("menuLabourQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Request.
        /// </summary>
        public static string menuLabourRequest {
            get {
                return ResourceManager.GetString("menuLabourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Sick Death.
        /// </summary>
        public static string menuLabourSickDeath {
            get {
                return ResourceManager.GetString("menuLabourSickDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota is not enough.
        /// </summary>
        public static string msgAppQuotaMore {
            get {
                return ResourceManager.GetString("msgAppQuotaMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select region, estate and on leave status.
        /// </summary>
        public static string msgChooseOnLeave {
            get {
                return ResourceManager.GetString("msgChooseOnLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data already exist.
        /// </summary>
        public static string msgExisting {
            get {
                return ResourceManager.GetString("msgExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No quota set at the moment.
        /// </summary>
        public static string msgNoLabourQuota {
            get {
                return ResourceManager.GetString("msgNoLabourQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not approve yet or already closed.
        /// </summary>
        public static string msgNotApproved {
            get {
                return ResourceManager.GetString("msgNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another batch request still pending process.
        /// </summary>
        public static string msgPendingProcess {
            get {
                return ResourceManager.GetString("msgPendingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota already used. Cannot delete..
        /// </summary>
        public static string msgQuotaUsed {
            get {
                return ResourceManager.GetString("msgQuotaUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string msgWait {
            get {
                return ResourceManager.GetString("msgWait", resourceCulture);
            }
        }
    }
}
